create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 40),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

alter table public.board_posts enable row level security;

drop policy if exists "Board posts are readable by everyone" on public.board_posts;
create policy "Board posts are readable by everyone"
  on public.board_posts
  for select
  using (true);

drop policy if exists "Anyone can create board posts" on public.board_posts;
create policy "Anyone can create board posts"
  on public.board_posts
  for insert
  with check (true);

grant select, insert on public.board_posts to anon;
