create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 40),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

alter table public.board_posts enable row level security;

drop policy if exists "Board posts are readable by everyone" on public.board_posts;
drop policy if exists "Authenticated users can read board posts" on public.board_posts;
create policy "Authenticated users can read board posts"
  on public.board_posts
  for select
  to authenticated
  using (auth.role() = 'authenticated');

drop policy if exists "Anyone can create board posts" on public.board_posts;
drop policy if exists "Authenticated users can create board posts" on public.board_posts;
create policy "Authenticated users can create board posts"
  on public.board_posts
  for insert
  to authenticated
  with check (auth.role() = 'authenticated');

create table if not exists public.registration_requests (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  email text not null check (char_length(trim(email)) between 3 and 120),
  area text not null check (area in ('市街地', '仏生山', '国分寺', '香南', '山田', '塩江', '牟礼', '屋島', '離島')),
  created_at timestamptz not null default now()
);

alter table public.registration_requests enable row level security;

drop policy if exists "Anyone can create registration requests" on public.registration_requests;
create policy "Anyone can create registration requests"
  on public.registration_requests
  for insert
  with check (true);

revoke select, insert on public.board_posts from anon;
grant select, insert on public.board_posts to authenticated;
